"use server";

import "server-only";
import { revalidatePath } from "next/cache";
import { and, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/lib/db/client";
import {
  completedGames,
  friendships,
  profiles,
  pushSubscriptions,
  puzzleAttempts,
  savedGames,
} from "@/lib/db/schema";
import { evaluateAndAwardAchievements } from "./achievements";
import { canonicalPair, getFriendship } from "./friends";
import { getCurrentUser } from "@/lib/supabase/server";
import { getDailyRankContext, getPuzzleById } from "@/lib/db/queries";
import { findConflicts, isCorrect, isFilled } from "@/lib/sudoku/validate";
import { parseBoard } from "@/lib/sudoku/board";
import { nextHint } from "@/lib/sudoku/solver";
import { dailyCompare, eventLog, solveTimeSanity } from "@/lib/flags";
import {
  HINT_BUCKET,
  HINT_LIMITS,
  checkRateLimit,
  rateLimitActorKey,
  recordRateLimitEvent,
} from "@/lib/server/rate-limit";

// All mutations go through Server Actions defined in this file. Every
// action validates inputs with Zod, derives the user from the cookie
// session (never trusts a userId from the caller), and performs the
// minimum DB work necessary.

const SaveSchema = z.object({
  puzzleId: z.number().int().positive(),
  board: z.string().length(81).regex(/^[0-9]{81}$/),
  notesB64: z.string().max(512).default(""),
  elapsedMs: z.number().int().nonnegative().max(24 * 60 * 60 * 1000),
  mistakes: z.number().int().nonnegative().max(999),
  hintsUsed: z.number().int().nonnegative().max(81),
  isPaused: z.boolean(),
});

export type SaveGameInput = z.infer<typeof SaveSchema>;

// Upsert the user's saved game for a puzzle. Called by the autosave
// effect on the play page; throttle on the client (we accept ~1 call
// every 3-5 seconds).
export async function saveGameAction(raw: SaveGameInput) {
  const user = await getCurrentUser();
  if (!user) return { ok: false as const, error: "unauthenticated" };

  const input = SaveSchema.parse(raw);

  // Check the puzzle exists; cheap because puzzles is a small frequently
  // cached table. Prevents a malicious or buggy client from creating
  // saved_games rows that point to nonexistent puzzles.
  const puzzle = await getPuzzleById(input.puzzleId);
  if (!puzzle) return { ok: false as const, error: "puzzle_not_found" };

  await db
    .insert(savedGames)
    .values({
      userId: user.id,
      puzzleId: input.puzzleId,
      board: input.board,
      notesB64: input.notesB64,
      elapsedMs: input.elapsedMs,
      mistakes: input.mistakes,
      hintsUsed: input.hintsUsed,
      isPaused: input.isPaused,
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: [savedGames.userId, savedGames.puzzleId],
      set: {
        board: input.board,
        notesB64: input.notesB64,
        elapsedMs: input.elapsedMs,
        mistakes: input.mistakes,
        hintsUsed: input.hintsUsed,
        isPaused: input.isPaused,
        updatedAt: new Date(),
      },
    });

  return { ok: true as const };
}

const SubmitSchema = z.object({
  puzzleId: z.number().int().positive(),
  board: z.string().length(81).regex(/^[0-9]{81}$/),
  elapsedMs: z.number().int().positive().max(24 * 60 * 60 * 1000),
  mistakes: z.number().int().nonnegative().max(999),
  hintsUsed: z.number().int().nonnegative().max(81),
  mode: z.enum(["random", "daily"]),
  dailyDate: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/)
    .optional()
    .nullable(),
  // RAZ-81: per-session idempotency token generated by the Zustand
  // game store (randomAttemptId). Optional so older clients that
  // haven't bundled the new code can still submit during the rolling
  // deploy — without it we lose dedupe protection for that one
  // request, which is the same behaviour we had before this ticket
  // and strictly better than rejecting the completion outright. The
  // length cap matches a UUID v4 string plus a comfortable margin
  // for the Math.random fallback shape (`<ts36>-<r1>-<r2>` ≈ 30
  // chars). Pattern is loose on purpose: we do NOT want to reject
  // a token format mismatch and lose the player's solve.
  attemptId: z.string().min(8).max(64).optional().nullable(),
});

export type SubmitInput = z.infer<typeof SubmitSchema>;

// Per-difficulty floor times in milliseconds. Anything faster than this
// is treated as suspicious and rejected from the leaderboard. Numbers
// are intentionally generous; we want to catch obvious cheating only.
const TIME_FLOOR_MS: Record<number, number> = {
  1: 30_000, // Easy: 30s
  2: 60_000, // Medium: 1m
  3: 90_000, // Hard: 1m30s
  4: 120_000, // Expert: 2m
};

// RAZ-27: how far the client-reported `elapsedMs` may exceed the
// wall-clock window `(now - saved_games.started_at)` before we reject
// the completion as tampered. 10% multiplicative slack + 2s additive
// slack. The multiplicative slack absorbs normal client/server clock
// drift and monotonic-clock rounding; the additive floor absorbs
// network latency on the submit round trip.
const SOLVE_TIME_MULT_SLACK = 1.1;
const SOLVE_TIME_ABS_SLACK_MS = 2_000;

// Submit a completion. The server is the SOLE source of truth for "did
// the user actually solve it". We compare the submitted board against the
// stored solution before recording anything.
export async function submitCompletionAction(raw: SubmitInput) {
  // RAZ-76: tagged logger so Vercel runtime logs show a clear trail
  // for every code path through this action. Without these we were
  // chasing a silent "completion modal showed but row never inserted"
  // bug across two database tables and three potential fail points
  // with literally zero server-side breadcrumbs (Vercel just showed
  // `POST /daily 200`). Every early-return now logs the error code
  // and the input puzzleId / mode so we can correlate against the
  // user's saved_games row.
  function log(stage: string, extra?: Record<string, unknown>) {
    console.log(
      `[submitCompletion] ${stage}`,
      JSON.stringify({
        puzzleId: raw?.puzzleId,
        mode: raw?.mode,
        elapsedMs: raw?.elapsedMs,
        ...extra,
      }),
    );
  }
  function fail<E extends string>(error: E, extra?: Record<string, unknown>) {
    console.warn(
      `[submitCompletion] reject:${error}`,
      JSON.stringify({
        puzzleId: raw?.puzzleId,
        mode: raw?.mode,
        elapsedMs: raw?.elapsedMs,
        ...extra,
      }),
    );
    return { ok: false as const, error };
  }

  const user = await getCurrentUser();
  if (!user) return fail("unauthenticated");

  let input: SubmitInput;
  try {
    input = SubmitSchema.parse(raw);
  } catch (err) {
    // Schema parse rejections previously bubbled as a thrown server
    // action error (HTTP 500-ish), which the client's IIFE then
    // silently swallowed because it had no try/catch. Convert to a
    // structured ok:false so the client's modal can show what went
    // wrong (e.g. dailyDate not in YYYY-MM-DD form).
    console.warn("[submitCompletion] reject:schema_invalid", err);
    return { ok: false as const, error: "schema_invalid" };
  }

  const puzzle = await getPuzzleById(input.puzzleId);
  if (!puzzle) return fail("puzzle_not_found");

  // Verify the submitted board. RAZ-18: use the puzzle's variant for
  // conflict detection so diagonal puzzles are validated correctly.
  const variant = (puzzle.variant ?? "standard") as import("@/lib/sudoku/board").Variant;
  const board = parseBoard(input.board);
  if (!isFilled(board) || findConflicts(board, variant).size > 0 || !isCorrect(board, puzzle.solution)) {
    return fail("incorrect_solution", {
      filled: isFilled(board),
      conflicts: findConflicts(board, variant).size,
      variant,
    });
  }

  // Time floor sanity check.
  if (input.elapsedMs < TIME_FLOOR_MS[puzzle.difficultyBucket]) {
    return fail("time_floor", { difficultyBucket: puzzle.difficultyBucket });
  }

  // RAZ-27: cross-check the client timer against server wall-clock
  // since the game's `started_at` (set by saved_games default on first
  // autosave). If the flag is off we skip the lookup entirely. If the
  // user has no saved_games row at all, this is a blitz solve that
  // finished before the first autosave fired; the per-difficulty floor
  // above is still protecting the leaderboard, so we don't block.
  if (await solveTimeSanity()) {
    const savedRow = await db
      .select({ startedAt: savedGames.startedAt })
      .from(savedGames)
      .where(and(eq(savedGames.userId, user.id), eq(savedGames.puzzleId, input.puzzleId)))
      .limit(1);
    const startedAt = savedRow[0]?.startedAt;
    if (startedAt) {
      const wallClockMs = Date.now() - startedAt.getTime();
      const maxAllowedMs = wallClockMs * SOLVE_TIME_MULT_SLACK + SOLVE_TIME_ABS_SLACK_MS;
      if (input.elapsedMs > maxAllowedMs) {
        return fail("solve_time_mismatch", {
          wallClockMs,
          maxAllowedMs,
        });
      }
    }
  }

  // For daily, verify the daily_date matches what we have on file (so
  // a player can't backdate a daily completion to a different day).
  let dailyDate: string | null = null;
  if (input.mode === "daily") {
    if (!input.dailyDate) return fail("missing_daily_date");
    const today = todayUtc();
    if (input.dailyDate !== today) {
      return fail("daily_date_mismatch", {
        client: input.dailyDate,
        server: today,
      });
    }
    dailyDate = today;
  }

  // Insert; the unique index on (user_id, daily_date) where mode='daily'
  // enforces "one scored daily per user per day" at the DB level. The
  // partial unique index on attempt_id (RAZ-81) additionally enforces
  // "one row per per-session idempotency token" so a flaky-network
  // retry storm cannot pollute the random-mode leaderboard.
  try {
    await db.insert(completedGames).values({
      userId: user.id,
      puzzleId: input.puzzleId,
      difficultyBucket: puzzle.difficultyBucket,
      timeMs: input.elapsedMs,
      mistakes: input.mistakes,
      hintsUsed: input.hintsUsed,
      mode: input.mode,
      dailyDate,
      attemptId: input.attemptId ?? null,
    });
    log("inserted", { userId: user.id, attemptId: input.attemptId ?? null });
  } catch (e: unknown) {
    // Unique violation. We need to know WHICH unique index fired:
    //   - `completed_games_daily_user_bucket_uniq` → the player already
    //     scored today's daily for this difficulty (legitimate reject).
    //   - `completed_games_attempt_id_uniq` (RAZ-81) → the same
    //     play-session token already inserted a row, almost certainly
    //     because this is a retry of a previous submit that DID land
    //     on the server but whose response the client never saw
    //     (network blip, cancelled RSC POST, page reload during the
    //     spinner, etc.). Treat this as success and return the same
    //     ok-shaped response so the caller's modal doesn't flip into
    //     an error state for a solve that was already recorded.
    const dbErr = e as { code?: string; constraint?: string; constraint_name?: string } | null;
    if (dbErr && dbErr.code === "23505") {
      const constraint = dbErr.constraint ?? dbErr.constraint_name ?? "";
      if (constraint === "completed_games_attempt_id_uniq") {
        log("idempotent_replay", { attemptId: input.attemptId ?? null });
        // Fall through past the insert block. The rest of the action
        // (saved_games cleanup, revalidatePath, rank context,
        // achievements) is safe to re-run on a duplicate submit:
        //   - delete saved_games is idempotent
        //   - revalidatePath is idempotent
        //   - rank context is a read-only lookup
        //   - achievements re-evaluation is keyed on (user, key) and
        //     will simply find them already earned
      } else {
        return fail("already_completed_today");
      }
    } else {
      // RAZ-76: surface every other DB error to the runtime logs before
      // re-throwing. Previously these threw straight up to the client
      // IIFE which had no catch, so the modal showed "Solved!" and the
      // log just said `POST /daily 200`. Now we get a proper trail.
      console.error("[submitCompletion] insert_failed", e);
      throw e;
    }
  }

  // Saved game is no longer needed; clean it up so the dashboard's
  // "Continue" card doesn't show a finished puzzle. Wrapped so a
  // delete failure (rare — would only happen on a connection blip
  // between the insert and this statement) cannot mask the fact
  // that the row IS inserted; we just log and continue. The user
  // experience of "I see the completion in the modal but the
  // continue card on /play also still shows it" is much smaller
  // than "completion silently doesn't count".
  try {
    await db
      .delete(savedGames)
      .where(and(eq(savedGames.userId, user.id), eq(savedGames.puzzleId, input.puzzleId)));
  } catch (err) {
    console.error("[submitCompletion] saved_games delete_failed", err);
  }

  // Invalidate the leaderboard and dashboard caches so the new entry
  // shows up immediately on the next request. RAZ-74: a plain
  // `revalidatePath("/profile")` only invalidates the literal
  // `/profile` segment (a thin redirect page) — it does NOT
  // propagate to the *dynamic* `/profile/[username]` page where the
  // stats actually render. Per the Next 15 docs, dynamic segments
  // need either an explicit `[param]` placeholder + the `"page"`
  // type, or a `"layout"` revalidation higher up the tree. Same
  // shape for the per-difficulty + quick leaderboard variants.
  //
  // RAZ-76: wrapped because `revalidatePath` is documented to throw
  // on invalid path syntax (and silently no-ops in dev). We don't
  // want a future typo here to bring down the entire submit chain.
  try {
    revalidatePath("/leaderboard");
    revalidatePath("/leaderboard/quick");
    revalidatePath("/leaderboard/difficulty/[bucket]", "page");
    revalidatePath("/profile");
    revalidatePath("/profile/[username]", "page");
    revalidatePath("/play");
  } catch (err) {
    console.error("[submitCompletion] revalidatePath_failed", err);
  }

  // RAZ-32: compute a rank context AFTER the insert so the caller is
  // counted in the denominator. Only for daily mode (the feature is
  // framed around "today's solvers" — a per-puzzle rank context for
  // random puzzles exists in the per-difficulty leaderboard already).
  // Flag off or non-daily mode → null and the modal simply hides the
  // banner. We swallow errors defensively: a failed rank lookup must
  // not mask the fact that the completion itself was recorded
  // successfully.
  let rankContext:
    | { total: number; slower: number; percentile: number }
    | null = null;
  if (input.mode === "daily" && dailyDate && (await dailyCompare())) {
    try {
      // RAZ-33: scope rank context to this tier so "you beat 73%
      // of today's solvers" compares like-with-like — a Medium
      // solver shouldn't be ranked against Easy solvers.
      rankContext = await getDailyRankContext(
        dailyDate,
        input.elapsedMs,
        puzzle.difficultyBucket,
      );
    } catch {
      rankContext = null;
    }
  }

  // RAZ-10: evaluate achievements AFTER the completion is recorded
  // (and profile streak fields have been updated by the SQL
  // trigger). Swallow errors: failing to award a badge must not
  // mask the successful completion. We log on the server so the
  // omission is at least observable. The returned list is the
  // set of badges newly earned on THIS call — the client uses it
  // to show a celebratory toast.
  let newlyEarned: { key: string; title: string; icon: string }[] = [];
  try {
    const defs = await evaluateAndAwardAchievements(user.id);
    newlyEarned = defs.map((d) => ({
      key: d.key,
      title: d.title,
      icon: d.icon,
    }));
  } catch (err) {
    console.error("evaluateAndAwardAchievements failed", err);
  }

  return { ok: true as const, rankContext, newlyEarned };
}

// RAZ-28 — Flush the in-memory input-event buffer to `puzzle_attempts`.
// Separate action (rather than piggybacking on saveGameAction /
// submitCompletionAction) for three reasons:
//   1. The client gets to decide when to flush independently of
//      saving — e.g. we can let autosave throttle at 4s while
//      flushes ride a longer 15s debounce to keep DB write rate low.
//   2. A flush failure must never block an autosave or a completion
//      submit. Keeping them separate means the failure blast radius
//      is local to the event log.
//   3. Simpler to audit / revert. We can flip the `event-log` flag
//      off in Edge Config and this endpoint immediately no-ops,
//      without touching the hot paths.
//
// The wire payload is kept small: up to EVENT_BUFFER_CAP events per
// flush, each ~20-40 bytes on the wire. A typical 200-event attempt
// therefore costs a single ~8 KB row in puzzle_attempts.
//
// Events are inserted with `event='input_batch'` and a jsonb payload
// of `{seq, completed, events}`. Multiple rows per (user, puzzle) are
// expected — the server stitches them by (puzzle_id, seq) when
// reconstructing a replay.
//
// The row is allowed to land with `user_id = null` for anonymous
// players (matches the RLS policy). Signed-in players get their
// user_id recorded so downstream replay / profile views can filter.
const InputEventSchema = z.object({
  c: z.number().int().min(0).max(80),
  d: z.number().int().min(0).max(9),
  t: z.number().int().nonnegative().max(24 * 60 * 60 * 1000),
  k: z.enum(["v", "e", "h"]),
});

const FlushSchema = z.object({
  puzzleId: z.number().int().positive(),
  seq: z.number().int().nonnegative(),
  completed: z.boolean(),
  // Match the in-memory EVENT_BUFFER_CAP (1024) — any more per flush
  // and we'd be accepting more than the client could have captured.
  // Zod rejects the whole batch if any event is malformed rather
  // than silently truncating, which is the right tradeoff: a
  // corrupted batch signals a client bug we want to surface in logs.
  events: z.array(InputEventSchema).max(1024),
});

export type FlushInputEventsInput = z.infer<typeof FlushSchema>;

export async function flushInputEventsAction(raw: FlushInputEventsInput) {
  // Flag gate first — when off we just drop the payload on the floor.
  // We return ok so the client doesn't retry or surface a spurious
  // error to the user; the contract for this endpoint is "fire and
  // forget" from the client's point of view.
  if (!(await eventLog())) return { ok: true as const, written: false };

  const input = FlushSchema.parse(raw);

  // Tolerate an empty completion-marker flush: the client may want
  // to mark the end of an attempt even if it already drained the
  // last events batch. We still insert the row because the `completed`
  // flag is itself a signal downstream consumers want.
  if (input.events.length === 0 && !input.completed) {
    return { ok: true as const, written: false };
  }

  // Puzzle existence check — same pattern as saveGameAction. Keeps
  // the table tidy: no events for puzzle_ids we don't have records
  // for. Cheap because puzzles is small + cached.
  const puzzle = await getPuzzleById(input.puzzleId);
  if (!puzzle) return { ok: false as const, error: "puzzle_not_found" };

  // Anonymous writes are legal per RLS; we pass null in that case.
  const user = await getCurrentUser();

  await db.insert(puzzleAttempts).values({
    userId: user?.id ?? null,
    puzzleId: input.puzzleId,
    event: "input_batch",
    payload: {
      seq: input.seq,
      completed: input.completed,
      events: input.events,
    },
  });

  return { ok: true as const, written: true };
}

const HintSchema = z.object({
  puzzleId: z.number().int().positive(),
  board: z.string().length(81).regex(/^[0-9]{81}$/),
  selected: z.number().int().min(0).max(80).nullable(),
});

export type HintInput = z.infer<typeof HintSchema>;

// Server-side hint endpoint, used for daily puzzles where we don't
// ship the solution to the client.
//
// RAZ-29: wrapped in a rate limiter (3/min, 30/hour, per actor). Daily
// puzzles keep the solution server-side specifically to prevent
// scraping; without a rate limit a bot could hit this endpoint once
// per cell and reconstruct the board. We bill the quota AFTER we've
// decided the request is honest (valid schema, known puzzle) so a
// malformed request doesn't burn through a legitimate player's quota
// by accident.
export async function hintAction(raw: HintInput) {
  const input = HintSchema.parse(raw);

  // Validate puzzle existence FIRST. A 404 on puzzle_not_found shouldn't
  // count against the actor's quota — that's a client-state bug, not
  // abuse.
  const puzzle = await getPuzzleById(input.puzzleId);
  if (!puzzle) return { ok: false as const, error: "puzzle_not_found" };

  // Resolve the rate-limit key. For signed-in users this is user_id;
  // for anon callers we hash their forwarded-for IP. Either way the
  // limit is PER ACTOR so one abusive user can't DoS others.
  const user = await getCurrentUser();
  const key = await rateLimitActorKey(user?.id ?? null);
  const decision = await checkRateLimit(HINT_BUCKET, key, HINT_LIMITS);
  if (!decision.ok) {
    return {
      ok: false as const,
      error: "rate_limited" as const,
      retryAfterMs: decision.retryAfterMs,
      limit: decision.window.label,
    };
  }

  const board = parseBoard(input.board);
  const suggestion = nextHint(board, {
    selected: input.selected,
    solution: puzzle.solution,
  });
  if (!suggestion) return { ok: false as const, error: "no_hint" };

  // Record AFTER we've committed to returning a real hint. If the
  // puzzle is already solved (no_hint) we don't charge the quota —
  // that's a legitimate no-op the UI surfaces as "no more hints
  // needed" rather than abuse.
  await recordRateLimitEvent(HINT_BUCKET, key);

  return {
    ok: true as const,
    index: suggestion.index,
    digit: suggestion.digit,
    technique: suggestion.technique,
  };
}

const UpdateProfileSchema = z.object({
  username: z
    .string()
    .min(3)
    .max(24)
    .regex(/^[a-z0-9_-]+$/),
  displayName: z.string().max(40).optional(),
});

// Set username and display name. Username has a unique constraint, so a
// duplicate returns a sentinel error the form can surface inline.
export async function updateProfileAction(raw: z.infer<typeof UpdateProfileSchema>) {
  const user = await getCurrentUser();
  if (!user) return { ok: false as const, error: "unauthenticated" };
  const input = UpdateProfileSchema.parse(raw);

  try {
    const { profiles } = await import("@/lib/db/schema");
    await db
      .update(profiles)
      .set({ username: input.username, displayName: input.displayName ?? input.username })
      .where(eq(profiles.id, user.id));
  } catch (e: unknown) {
    if (typeof e === "object" && e && "code" in e && (e as { code: string }).code === "23505") {
      return { ok: false as const, error: "username_taken" };
    }
    throw e;
  }
  revalidatePath("/profile");
  return { ok: true as const };
}

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

const MigrateSchema = z.object({
  // The anonymous game from localStorage. Only the active in-progress
  // game is migrated by default; if it turns out to be already
  // solved, RAZ-76 also records a completion so anonymous wins are
  // not silently dropped on sign-in.
  saved: z
    .object({
      puzzleId: z.number().int().positive(),
      board: z.string().length(81).regex(/^[0-9]{81}$/),
      notesB64: z.string().max(512),
      elapsedMs: z.number().int().nonnegative(),
      mistakes: z.number().int().nonnegative(),
      hintsUsed: z.number().int().nonnegative(),
      isPaused: z.boolean(),
      // RAZ-76: optional metadata so we can promote a completed
      // anonymous solve into a real `completed_games` row. Both
      // fields are optional for backward-compat with older
      // localStorage payloads — when missing, we fall back to
      // "random" mode and skip the daily-date check.
      mode: z.enum(["random", "daily"]).optional(),
      dailyDate: z
        .string()
        .regex(/^\d{4}-\d{2}-\d{2}$/)
        .optional()
        .nullable(),
    })
    .nullable(),
});

// Migrate an anonymous user's local progress into their new account on
// first sign-in. Conservative: only preserves the active in-progress
// game. Old completions stay in localStorage but never reach the server,
// so the leaderboard can't be polluted with anonymous wins.
//
// RAZ-76: previously this action SILENTLY dropped any anonymous solve
// — it only ever wrote to `saved_games`. Players who finished a puzzle
// before signing in (or while their session was briefly missing due
// to OAuth refresh) would see the local "Solved!" modal, then a
// profile page that said zero. We now detect a fully-solved board on
// the way in and promote it to a real completion via the same
// validation path the live submit uses, so the player gets credit for
// what they already saw on screen. Random mode only — daily auto-
// promotion would race the daily_date_mismatch / unique-index gates
// and is not worth the corner-case complexity for a path that's
// expected to be rare.
export async function migrateLocalProgressAction(raw: z.infer<typeof MigrateSchema>) {
  const user = await getCurrentUser();
  if (!user) return { ok: false as const, error: "unauthenticated" };
  const input = MigrateSchema.parse(raw);

  if (!input.saved) return { ok: true as const };

  const puzzle = await getPuzzleById(input.saved.puzzleId);
  if (!puzzle) return { ok: false as const, error: "puzzle_not_found" };

  // RAZ-76: detect a completed local snapshot. We require BOTH a
  // fully-filled board AND zero conflicts AND an exact match against
  // the stored solution — same triple-gate the live submit path uses
  // — so we can never accidentally credit a partial / cheated /
  // wrong-puzzle board.
  const variant = (puzzle.variant ?? "standard") as import("@/lib/sudoku/board").Variant;
  const localBoard = parseBoard(input.saved.board);
  const isLocallySolved =
    isFilled(localBoard) &&
    findConflicts(localBoard, variant).size === 0 &&
    isCorrect(localBoard, puzzle.solution);

  if (isLocallySolved) {
    // Promote to a real completion via the live action. Reusing the
    // action (rather than inlining the insert) keeps the time-floor,
    // sanity, achievements, and revalidation behavior in lockstep so
    // a future change to one path automatically benefits the other.
    // We force `mode = "random"` defensively (see the function
    // comment) so daily-mode invariants stay intact.
    const submit = await submitCompletionAction({
      puzzleId: input.saved.puzzleId,
      board: input.saved.board,
      elapsedMs: input.saved.elapsedMs,
      mistakes: input.saved.mistakes,
      hintsUsed: input.saved.hintsUsed,
      mode: "random",
      dailyDate: null,
    });
    // The submit action also deletes the matching saved_games row on
    // success, so we don't have to. On any failure (time floor,
    // already_completed, transient DB blip) we fall through to the
    // saved_games preservation path so the player at minimum keeps
    // their progress to retry from.
    if (submit.ok) return { ok: true as const, promoted: true };
    console.warn(
      "[migrate] auto-submit refused, falling back to saved_games",
      JSON.stringify({ puzzleId: input.saved.puzzleId, error: submit.error }),
    );
  }

  // If the user already has a saved game for this puzzle, preserve the
  // server copy (it's been autosaved across devices and is more
  // trustworthy than the local one).
  const existing = await db
    .select()
    .from(savedGames)
    .where(and(eq(savedGames.userId, user.id), eq(savedGames.puzzleId, input.saved.puzzleId)))
    .limit(1);
  if (existing[0]) return { ok: true as const, kept: "server" };

  await db.insert(savedGames).values({
    userId: user.id,
    puzzleId: input.saved.puzzleId,
    board: input.saved.board,
    notesB64: input.saved.notesB64,
    elapsedMs: input.saved.elapsedMs,
    mistakes: input.saved.mistakes,
    hintsUsed: input.saved.hintsUsed,
    isPaused: input.saved.isPaused,
    updatedAt: new Date(),
  });
  return { ok: true as const, kept: "local" };
}

// =============================================================================
// RAZ-12 — Friend requests / private leaderboards.
// =============================================================================

// Usernames are lowercase-ish alphanumeric + dash + underscore.
// We don't enforce this at the DB level for the profiles table
// (existing profiles may have mixed case) but we normalise here
// so "@RAZ" and "@raz" resolve the same way.
const UsernameSchema = z
  .string()
  .min(1)
  .max(40)
  .regex(/^[A-Za-z0-9_\-.]+$/);

/**
 * Send a friend request by username. Idempotent in the sense that
 * re-sending a request from the same pending row is a no-op;
 * re-sending after the recipient declined (which deleted the row)
 * starts a fresh request.
 */
export async function sendFriendRequestAction(rawUsername: string) {
  const me = await getCurrentUser();
  if (!me) return { ok: false as const, error: "unauthenticated" };

  const parsed = UsernameSchema.safeParse(rawUsername.trim());
  if (!parsed.success) return { ok: false as const, error: "invalid_username" };

  // Username lookups are case-insensitive; most users type "@Raz"
  // when they mean "@raz". We lower() both sides for the compare.
  const target = await db
    .select({ id: profiles.id, username: profiles.username })
    .from(profiles)
    .where(sql`lower(${profiles.username}) = lower(${parsed.data})`)
    .limit(1);

  if (!target[0]) return { ok: false as const, error: "user_not_found" };
  const other = target[0].id;
  if (other === me.id) return { ok: false as const, error: "cannot_friend_self" };

  const existing = await getFriendship(me.id, other);
  if (existing) {
    if (existing.status === "accepted")
      return { ok: false as const, error: "already_friends" };
    if (existing.status === "pending")
      return { ok: false as const, error: "already_pending" };
    if (existing.status === "blocked")
      return { ok: false as const, error: "blocked" };
  }

  const { userA, userB } = canonicalPair(me.id, other);
  await db.insert(friendships).values({
    userA,
    userB,
    status: "pending",
    requestedBy: me.id,
    updatedAt: new Date(),
  });

  revalidatePath("/friends");
  return { ok: true as const };
}

/**
 * Accept an incoming friend request. The `fromUserId` is the
 * initiator — the one whose row has `requested_by = fromUserId`.
 * We never let the initiator accept their own request (would
 * defeat the point), and we require the pending row to actually
 * exist.
 */
export async function acceptFriendRequestAction(fromUserId: string) {
  const me = await getCurrentUser();
  if (!me) return { ok: false as const, error: "unauthenticated" };

  const { userA, userB } = canonicalPair(me.id, fromUserId);
  const updated = await db
    .update(friendships)
    .set({ status: "accepted", updatedAt: new Date() })
    .where(
      and(
        eq(friendships.userA, userA),
        eq(friendships.userB, userB),
        eq(friendships.status, "pending"),
        // Only the non-initiator can accept — prevents the
        // sender from self-accepting via a crafted action call.
        eq(friendships.requestedBy, fromUserId),
      ),
    )
    .returning({ userA: friendships.userA });

  if (updated.length === 0)
    return { ok: false as const, error: "request_not_found" };

  revalidatePath("/friends");
  revalidatePath("/leaderboard");
  return { ok: true as const };
}

/**
 * Decline an incoming request OR cancel an outgoing one OR remove
 * an accepted friend. All three are modelled as "delete the row"
 * because the friendship table doesn't keep history beyond the
 * current state. The caller must be a party; safe against
 * arbitrary-user deletion because of that `or()` predicate.
 */
export async function removeFriendshipAction(otherUserId: string) {
  const me = await getCurrentUser();
  if (!me) return { ok: false as const, error: "unauthenticated" };

  const { userA, userB } = canonicalPair(me.id, otherUserId);
  const deleted = await db
    .delete(friendships)
    .where(
      and(eq(friendships.userA, userA), eq(friendships.userB, userB)),
    )
    .returning({ userA: friendships.userA });

  if (deleted.length === 0)
    return { ok: false as const, error: "not_found" };

  revalidatePath("/friends");
  revalidatePath("/leaderboard");
  return { ok: true as const };
}

// ---------------------------------------------------------------------------
// RAZ-7: Push subscription management
// ---------------------------------------------------------------------------

const PushSubSchema = z.object({
  endpoint: z.string().url(),
  keys: z.object({
    p256dh: z.string().min(1),
    auth: z.string().min(1),
  }),
});

const SubscribeSchema = z.object({
  subscription: PushSubSchema,
  timezone: z.string().max(80).default("UTC"),
  notifyAt: z
    .string()
    .regex(/^\d{2}:\d{2}$/)
    .default("09:00"),
});

/**
 * Save (or update) the user's push subscription. Called when the
 * client successfully subscribes via PushManager. We upsert on
 * (user_id, endpoint) so re-subscribing from the same browser
 * replaces the old row rather than duplicating it.
 */
export async function subscribePushAction(raw: {
  subscription: { endpoint: string; keys: { p256dh: string; auth: string } };
  timezone?: string;
  notifyAt?: string;
}) {
  const user = await getCurrentUser();
  if (!user) return { ok: false as const, error: "unauthenticated" };

  const input = SubscribeSchema.parse(raw);

  await db
    .insert(pushSubscriptions)
    .values({
      userId: user.id,
      endpoint: input.subscription.endpoint,
      subJson: input.subscription,
      timezone: input.timezone,
      notifyAt: input.notifyAt,
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: [pushSubscriptions.userId, pushSubscriptions.endpoint],
      set: {
        subJson: input.subscription,
        timezone: input.timezone,
        notifyAt: input.notifyAt,
        updatedAt: new Date(),
      },
    });

  revalidatePath("/profile/edit");
  return { ok: true as const };
}

/**
 * Remove all push subscriptions for the current user. Called when
 * they toggle off daily reminders (we unsubscribe client-side too,
 * but removing the server rows is the source of truth that prevents
 * further sends).
 */
export async function unsubscribePushAction() {
  const user = await getCurrentUser();
  if (!user) return { ok: false as const, error: "unauthenticated" };

  await db
    .delete(pushSubscriptions)
    .where(eq(pushSubscriptions.userId, user.id));

  revalidatePath("/profile/edit");
  return { ok: true as const };
}
